### ISSUE TITLE
The viewer does not support closed topologies

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [sulcgroup/oxdna-viewer#1]
Neither the master nor the dev branch supports closed topologies. In the dev branch, the issue can be worked around by using -1 in place of the n3 neighbour of the first nucleotide and of the n5 neighbour of the last nucleotide, even when the topology contains more than a closed strand. By contrast, the master branch requires all strands to be open.

**Comment by ErikPoppleton** [comment]
Thank you for pointing that out!  As of now, the dev branch no longer crashes on circular topologies, although it does not correctly display the connection.  Fixing that error and then porting to the main branch.

**Comment by ErikPoppleton** [comment]
The file parsing on the dev branch has been completely rewritten.  It can now handle circular topologies as well as large trajectory files without crashing!  Let me know if you find any more issues with files that it can/cannot read.
