### ISSUE TITLE
OxView (web-version) really slow? 

### ISSUE THREAD

**Issue by Boyu-Liu03** [sulcgroup/oxdna-viewer#117]
Hi I'm not sure what is going on but OxView seemed really slow for me today--like I have perhaps one frame per second when just dragging an origami design around, and tested on multiple computers. I checked hardware-acceleration to be on as well.

**Comment by ErikPoppleton** [comment]
OxView is entirely a client-side application, are you sure that you don't have anything eating a ton of memory on your computer?  I made some changes to file read/write yesterday, but nothing to do with the renderer.  I just checked Chrome, Firefox and Safari and am not having any rendering slowdown on my side.  What kind of operating system/browser are you using?

**Comment by ErikPoppleton** [comment]
If you want to double check that nothing I did somehow affected rendering, you can serve an instance of oxView locally and try checking out commit 47010db376e76c7e46d0e00c623b3966ead8908d

**Comment by Boyu-Liu03** [comment]
Hi Eric--I think you are right with the memory; I checked on activity monitor and 7.9G of my 8GB of memory was being used. I'm on a 2017 mac air with MacOS 12.6.7 (21G651) using the newest version Chrome. Is there a recommended memory requirement for running OxView with big design files and trajectory files then?

**Comment by Boyu-Liu03** [comment]
Also the thing appeared really weird to me as I've been successfully using OxView on this laptop for months without this kind of lagging, until yesterday.

**Comment by ErikPoppleton** [comment]
Is it oxView that is consuming all the memory?  I checked after you sent me this that I could still load big (1.6 million nucleotides) files.  My computer didn't like that, but the browser tab will crash if you run your computer entirely out of memory.

**Comment by Boyu-Liu03** [comment]
I have no idea how to check that but I am web-browsing for how to.

**Comment by Boyu-Liu03** [comment]
https://github.com/sulcgroup/oxdna-viewer/assets/145397546/6aaad413-aaec-4bec-a9cf-643f113d1d69

Hi so I cleared a lot of the memory on my computer and ran Oxview again. Here's a screen-recording?

**Comment by ErikPoppleton** [comment]
Nothing looks strange there except the very slow rendering...

I am going to revert oxView back to before my last few days of work on the file reader.  Let's see if this fixes it for you.  I'll also try to get somebody in Arizona to help us out with testing which commit is breaking it so we're not desynced by timezones.

**Comment by ErikPoppleton** [comment]
We have managed to track down the problem as coming from an update to an external library... Trying to figure out how to work around it.

**Comment by Boyu-Liu03** [comment]
Hi Eric!! It worked! Thank you so much!

**Comment by Boyu-Liu03** [comment]
Really appreciate it!

**Comment by ErikPoppleton** [comment]
Okay, turns out it wasn't the external library.  I accidentally committed an increase in the resolution of the backbone spheres that I made when making a figure.  That has been reverted, the external library successfully updated, and the changes to file IO to support the [new topology format](https://lorenzo-rovigatti.github.io/oxDNA/configurations.html#topology-file) pushed to live.

**Comment by Boyu-Liu03** [comment]
Okay that's great to hear. Thanks again!
