### ISSUE TITLE
TacoxDNA importer dose not work

### ISSUE THREAD

**Issue by atlan-yf** [sulcgroup/oxdna-viewer#121]
All the buttons and checkbox in TacoxDNA importer is not responding.
Seems like the callback functions related with TacoxDNA importer elements are missing.
Here is the error in the console:

Uncaught ReferenceError: guessInputFormat is not defined
    at HTMLInputElement.onchange (index.html:172:131)
index.html:262  Uncaught ReferenceError: importFiles is not defined
    at HTMLButtonElement.onclick (index.html:262:117)

**Comment by ErikPoppleton** [comment]
Sorry about that!  I renamed some files and missed that file in the imports.  It's back up now.
