### ISSUE TITLE
I think the oxviewer is reading the box coordinates in the wrong order 

### ISSUE THREAD

**Issue by bensonbits** [sulcgroup/oxdna-viewer#15]
Hi, 

I'm trying to view a small file with a minimal rectangular box along the z-axis.

b = 4.0 4.0 13.36

This helix seems to get squeezed into a much smaller box, and it seems from playing around like the oxviewer has read the second coordinate (by) twice and is ignoring the third coordinate (bz).

Cheers

Erik

**Comment by bensonbits** [comment]
Ok, maybe oxviewer only supports square boxes and reads the second coordinate (by) ?

    box = parseFloat(lines[1].split(" ")[3]);

I would probably be better to use a square box with the size of the largest box side to prevent issues

**Comment by Akodiat** [comment]
Yes, you are correct in that currently only the second coordinate is read, I'll see what I can do!
