### ISSUE TITLE
Video exporting does not seem to work

### ISSUE THREAD

**Issue by MishraS-S** [sulcgroup/oxdna-viewer#19]
Hi

First of all I'd like to thank everyone for making this tool, this has made visualisation so much easier, it's a godsend.

I think I might be missing something very fundamental here but I seem to be having troubling getting the "Create Video" option to work. Essentially I have my .top and trajectory file loaded, and I can see and traverse through each frame of the simulation by pressing the arrow keys or by clicking the Next/Previous config buttons on the toolbar. 
However when I click on "Create Video" (with the default options selected, let's say video type trajectory, format webm and 24 fps) and click on the "Start" button, nothing seems to happen. I've tried this on a Windows and Linux machine, on Chrome and Firefox browsers, and both via server and locally and also using  .top and trajectory files from simulations of two very different structures.

Each time clicking the "Start" button gives the following message on Chrome and Firefox consoles respectively, regardless of the OS or structure being visualised.

"index.html:189 Uncaught ReferenceError: createVideo is not defined
    at HTMLButtonElement.onclick (index.html:189) "

"ReferenceError: createVideo is not defined"

Sorry if I'm missing something.

**Comment by ErikPoppleton** [comment]
Thanks for using it and catching that!  The video function works again.  Fixed in: 73c47aa3ca906d315b8977da7e32bb33d62ff2cb

**Comment by MishraS-S** [comment]
It is indeed working now, thanks for the quick fix!!
And thank you for the tool itself again !
