### ISSUE TITLE
Feature request - Adjust visibility/transparency for selections/clusters

### ISSUE THREAD

**Issue by MishraS-S** [sulcgroup/oxdna-viewer#20]
Hi

First of all thank you for making this amazing visualisation tool, it has made working with oxDNA simulations much easier and more intuitive, it has been a life saver. Having said that,  I would like to make a suggestion which I think could be a useful feature; the ability to adjust the transparency/visibility of selections or objects. I am not sure how much the userbase would benefit form such a feature so apologies if it would involve too much work to be worth it; in my specific use case, because I'm trying to look at dynamics of objects confined within enclosed structures such as boxes and barrels, I thought it would be nice if it were possible to observe the coformational changes only in the structure on the inside, that we're interested in.

Thanks

**Comment by ErikPoppleton** [comment]
Hi Mishrito, 

I can look into it later (transparency may not fly with the way we handle creating meshes without slowing it down at large structure sizes), but as a work around, there is a browser console command that will toggle visibility of particles.

1. Open the browser console (crtl-J on Chrome, ctrl-K on Firefox, at least on Ubuntu)
2. Create a list of particles you want to make invisible by typing:
`elems = api.getElements([<IDs of elements you want to make invisible>])`
3. Toggle the visibility of those elements:
`api.toggleElements(elems)`

There's also an option to toggle by strands which is slightly less intuitive and we really should improve:
1. Get the list of strands you want to make invisible (this is for contiguous strands, its going to be fancier JavaScript for non-contiguous strands):
`str = systems[0].strands.slice(start, end)`
2. Toggle the visibility of those strands:
`str.forEach((s) => {api.toggleStrand(s)})`

These two functions can for sure be streamlined into a sidebar button, we will take care of adding that.

Hope that helps!

Erik

**Comment by MishraS-S** [comment]
Hi Erik

Thank you so much for the quick response. I tried it and it does help a lot, being able to selectively toggle the visibility of specific strands. 

Thanks again !

**Comment by Akodiat** [comment]
To add to this, you can also just do `api.toggleElements(selectedBases)` to toggle the visibility of whatever you have selected. But it's safer to, as Erik writes, save the list of elements you want to toggle to a variable so you don't lose it if you select something else.

**Comment by MishraS-S** [comment]
Thank you for the tip! Using `selectedBases` and storing it again in a variable gives more options where one can toggle the option for arbitrary collections of objects, very useful!

**Comment by Akodiat** [comment]
Happy to be able to help :)
Since I realised it was a simple thing to add, there's now visibility toggle buttons in the System Hierarchy window, so you can click ![visibility](https://fonts.gstatic.com/s/i/materialicons/visibility/v1/24px.svg) and ![visibility_off](https://fonts.gstatic.com/s/i/materialicons/visibility_off/v1/24px.svg) to toggle the visibility of strands, etc.
You still need the command line for arbitrary selections though.

**Comment by MishraS-S** [comment]
Wow thanks a lot!

**Comment by ErikPoppleton** [comment]
Hi Mishrito, realized that I forgot to merge this feature branch in, but we now have a button in the "View" sidebar that will toggle the visibility of a selection.

**Comment by MishraS-S** [comment]
Thanks a lot !!
