### ISSUE TITLE
The highlight 5' end function seems like it isn't working.

### ISSUE THREAD

**Issue by MishraS-S** [sulcgroup/oxdna-viewer#22]
Hi, just quickly wanted to let you guys know that the highlight 5' function seems like it isn't working. This is the console output. 

```
api.hilight5ps()
VM63:1 Uncaught TypeError: api.hilight5ps is not a function
    at <anonymous>:1:5
(anonymous) @ VM63:1

```
Hopefully I'm not actually screwing up on my end haha

Thanks !

**Comment by m-matthies** [comment]
Hi, Mishrito thanks for pointing this one out. 
The function was misspelled in the code and misspelled in another way in your query. 
I changed it to be `highlight5ps()`.

**Comment by MishraS-S** [comment]
Thank you for the quick resolution! 
Oh sorry about that, I actually copied it from the "Console Commands" section in README.md.

**Comment by m-matthies** [comment]
I really appreciate the catch. ;)
