### ISSUE TITLE
Strands seem to be rendered at a fixed displaced position

### ISSUE THREAD

**Issue by MishraS-S** [sulcgroup/oxdna-viewer#23]
Hi! Again I would like to thank everyone working on this tool for making visualisation of oxDNA results so much easier.

I seem to have run into what looks like a visual bug. Essentially certain strands are rendered at a fixed position with a fixed distance from their actual position. I am attaching a video file (generated using the create video function in oxdna viewer), where you can see this happening. In addition the strands all start off in their correct position but change positions at some point during the trajectory traversal. This happens only when I am loading a trajectory, since if I open up say a single configuration file the strands are all in their correct positions. I have attached the config file of the last configuration in the video and you can see that it doesn't have the trail of strands shadowing the origami shape next to it. The files are all uploaded [here](https://drive.google.com/open?id=1QYmOn_9ZoMBU2NhG-1OIQB7vE27Pdtbb), since they were too big to attach and github doesn't allow video attachments anyways.

Thanks a lot again !

**Comment by ErikPoppleton** [comment]
Hi Mishrito,

I can't unzip your uploaded files.  Could you try uploading them again?  I suspect that you're encountering a bug with the periodic boundary conditions, but I would need to see the video to confirm.

**Comment by MishraS-S** [comment]
Hey thanks for the reply! Sorry, I reuploaded the files, which can be now found [here](https://drive.google.com/open?id=1gSmh9g3TrUY9upQGKJWprG7ovcAlblvI).

**Comment by ErikPoppleton** [comment]
Your box size is different in the first frame (550x550x550) vs in every other frame (500x500x500).  We only use the first frame to calculate periodic boundary conditions, so all the strands shifted by fix_diffusion are showing off as off by 50 units per time they got shifted.  Unfortunately, there are already strands that have been shifted before the second frame, so just deleting the first frame will not save the simulation.

**Comment by MishraS-S** [comment]
Hey thanks for looking into it! I can't seem to remember when or why the box size was changed but I guess it can't be helped. Thanks again and sorry about the mistake!
