### ISSUE TITLE
Colouring nucleotides by index

### ISSUE THREAD

**Issue by mckwxp** [sulcgroup/oxdna-viewer#24]
Hi,

I'd like to colour my nucleotides by index, something like "0-99 red, 100-199 blue", but I'm not sure how to script this. I'd be happy if anyone can help or provide an example.

Thanks,

Marco

**Comment by mckwxp** [comment]
I tried to follow the base occupancy example to make a "fake" occupancy json file for the colours. There seems to be a bug in the colour overlay. I got an error:

"Uncaught RangeError: Maximum call stack size exceeded
    at makeLut (file_reading.js:12)
    at readJson (file_reading.js:321)
    at FileReader.jsonReader.onload (file_reading.js:108)"

If I just change that line (file_reading.js:12) to "const min=0, max=1;", then it works well.

**Comment by ErikPoppleton** [comment]
Hi Marco,

Can you send me the your fake occupancy file and I'll take a look as to why it wasn't working?  You can also accomplish that using the browser console using the following command:

> a =  Array.from(Array(99).keys())  
> b = api.getElements(a)  
> b.forEach((n) => {  
>   n.toggle()  
> })  
> updateView()

which will select all the nucleotides between 0 and 99.  You can then use the "Label selection" option in the View tab on the sidebar.

When I get a chance I will make a quick way to change large numbers of particles from the console.

Best, 
Erik

**Comment by mckwxp** [comment]
Here's the json file. Apparently GitHub doesn't support json attachments, so I had to zip it. And actually I'm working with half a million nucleotides instead of 100. Not sure if that is causing the error.

[color.zip](https://github.com/sulcgroup/oxdna-viewer/files/4673141/color.zip)

**Comment by ErikPoppleton** [comment]
Ah, that makes the error make sense, it looks like you're hitting a limit in number of items that can be fed into the min function, which is a weird place for it to hit a wall.  I'll see if there's a better way to deal with that.  Out of curiosity, how long does that color file take to load?  Is the browser console method I gave faster or slower than using the file?

**Comment by mckwxp** [comment]
The color file is quite fast to load (just a few seconds) but the browser console method gave an error when I called updateView: 

"Uncaught TypeError: Cannot read property 'callUpdates' of undefined
    at updateView (base_selector.js:124)
    at <anonymous>:1:1"

If I don't call updateView, the console method works and is also very fast.

**Comment by ErikPoppleton** [comment]
I'm relieved that both methods are similar in performance.  If you don't mind, could you also send me the configuration/topology files you're trying to color with that json file you sent me (you can send it via slack if you don't want to post publicly) so I can test potential fixes?

**Comment by mckwxp** [comment]
I've sent them on Slack!
