### ISSUE TITLE
Strand generator gives wrong pointing bases

### ISSUE THREAD

**Issue by bensonbits** [sulcgroup/oxdna-viewer#25]
Hi Guys, 

It seems like something has happened to the strand generation feature, was working fine around a week ago. Now the bases are pointing away from the helix center instead of towards the center. 

Cheers

Erik B

**Comment by ErikPoppleton** [comment]
We have somebody working on it (and adding the ability to create double strands).  Will hopefully be done soon.  It was happening before too, something to do with calculating the a1 vectors wrong in certain cases.

**Comment by ErikPoppleton** [comment]
Its fixed and there is now the ability to add double strands in addition to single strands!
