### ISSUE TITLE
Json overlay not working

### ISSUE THREAD

**Issue by marlol4** [sulcgroup/oxdna-viewer#26]
Hi, it appears that the .json overlay stopped working. It was working a few hours ago. 
Cheers,
Marco

**Comment by ErikPoppleton** [comment]
Hi Marco, I'm trying to figure out what's going on.  If you need it working again and have a local copy of oxView, it looks like commit  f5045fb09abadc1ae32c350cb8ee5600ebc7379c broke the overlay system, so commit fda690356f5459bad8cc5515fd0c9275bc533aeb will work.  If I can't figure out what's going on, @Akodiat will have to take a look in the morning.

**Comment by ErikPoppleton** [comment]
Hi Marco, it should be fixed now.  Thanks for catching that.
