### ISSUE TITLE
oxDNA export mac osx / safari

### ISSUE THREAD

**Issue by JonathanBath** [sulcgroup/oxdna-viewer#28]
when exporting oxDNA files if both topology and configuration check boxes are selected, only the configuration is exported (files can be exported one at a time without problem)

when I remember, I use chrome!

**Comment by Akodiat** [comment]
@AatmikMallya Could you maybe have a look at this on osx when you get the time? I'm not able to reproduce it on linux

**Comment by Akodiat** [comment]
I think we can close this now, right? @AatmikMallya
