### ISSUE TITLE
Uncaught TypeError: cannot read property "r" of undefined

### ISSUE THREAD

**Issue by pepigomez95** [sulcgroup/oxdna-viewer#30]
![image](https://user-images.githubusercontent.com/53091727/92338456-2f624d00-f076-11ea-8058-9982b50772c6.png)

Hello! I'm getting an error when trying to upload my files after using DNAnalysis (hydrogen bond occupancy) to oxview. The error is shown in the image above which includes the console.

The files i'm using are in the link below:
[bondanalysis.zip](https://github.com/sulcgroup/oxdna-viewer/files/5180514/bondanalysis.zip)

**Comment by m-matthies** [comment]
Hi, from the looks of it your bond analysis file has just 0 values. 
Please double check the way you start the analysis script.
