### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by DurhamSmith** [sulcgroup/oxdna-viewer#31]
Hello, 

I would like to run this locally, are there any instructions on how to get started? Linux/Ubuntu please!

**Comment by m-matthies** [comment]
Hello, 
Depending on wherever you plan to extend the code or just use the tool locally you have several options. 

- The package we typically use for developing ox-view is [reload](https://www.npmjs.com/package/reload)  which requires a [node.js](https://nodejs.org/en/) installation.

- Another option, if you are just interested in using the tool locally and have python installed you could 
use the python http server, just go to the ox-view directory and execute. 
> python -m http.server 8000

Than you can open any supported browser and ox-view  will be available @ [localhost:8000](http://localhost:8000/) 

-  Option 3 would be to configure nginx or apache ;) 

Hope this brings you further.

**Comment by DurhamSmith** [comment]
Thanks!
