### ISSUE TITLE
Modify render hierarchy. 

### ISSUE THREAD

**Issue by zoombya** [sulcgroup/oxdna-viewer#4]
At current stage we have the system model separate from the threejs objects.
If we inherit system/strand/nucleotide  from the threejs group we can simplify code.

**Comment by sshar118** [comment]
![IMG_20190626_110518207](https://user-images.githubusercontent.com/39283189/60216731-b0417a00-981f-11e9-8dd1-e2e6e2fc2901.jpg)
![IMG_20190626_110526155](https://user-images.githubusercontent.com/39283189/60216732-b0417a00-981f-11e9-9529-055f681077fa.jpg)
