### ISSUE TITLE
Save colour palette

### ISSUE THREAD

**Issue by Akodiat** [sulcgroup/oxdna-viewer#41]
It would be nice to be able to use a customized colour scheme. Could be saved to the .oxview file and/or to a separate file for easier re-use.

I'll look into this when I find the time

**Comment by ErikPoppleton** [comment]
One thought I've been having recently is to create some sort of "command file" that would let you save a sequence of commands to make re-execution easy.  Maybe something like
```
{
    commandSequence : {
        selectElementsById : [1,2,3],
        setSelectedColor : 0xFF0000
    }
}
```
