### ISSUE TITLE
findPair() is not restrictive enough in distance

### ISSUE THREAD

**Issue by mmguar** [sulcgroup/oxdna-viewer#46]
Let's imagine a system like strands[0] "AA" and a complementary strands[1] "T". Then the distance between strands[0].getMonomers()[1] and strands[1].getMonomers()[0] is 0.5447186694727051, which is less than the minimum distance required by findPair() to accept a pair (0.6).
I am sure that there are reasons for this, but this makes the default behavior of functions such as edit.createBP wrong as they have a check for findPair(), which, if the same base is repepated twice, fails because the second base is considered paired to the complement of the first one, incorrectly.
I thought of using the isPaired() check instead, but that have not been explicitly paired.

**Comment by ErikPoppleton** [comment]
Thanks for pointing this out.  We were using a simple distance cutoff, which as you point out is too permissive.  To fix this, I took a look at the a1 orientation vectors between all pairs in a trajectory.  This analysis showed that almost all paired nucleotides have a dot product between their a1 vectors below -0.95.

![image](https://user-images.githubusercontent.com/36451772/122477887-4dea6280-cf7d-11eb-8161-5f9c0d2595f6.png)

However, there are values as low as -0.77.  I took a look at your pathologic case, which has a value of -0.81, so I set a cutoff of -0.85 and it fixes your problem and should result in relatively few missed connections.  Hopefully will be fixed now.
