### ISSUE TITLE
Select a strand in System Hierarchy does not highlight it anymore 

### ISSUE THREAD

**Issue by RodenLuo** [sulcgroup/oxdna-viewer#52]
Hi, There was this I thought very nice feature. But it is no longer effective. Not sure if this is intentional or not. 

![image](https://user-images.githubusercontent.com/8460424/124740360-67028580-df23-11eb-869f-35fe7dc3632b.png)
 

Mac OS 10.15.7
Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by RodenLuo** [comment]
Oh, sorry, I realized that I have to move my mouse to the scene to let it take effect. (I remember it was not like this before. It was in effect right after I check the box)

**Comment by m-matthies** [comment]
Hi, Roden. I think we might have missed a render call there.
We are doing heavy refactoring at the moment, so if you notice anything else breaking
please let us know ;)
