### ISSUE TITLE
No configuration shown

### ISSUE THREAD

**Issue by ohenrich** [sulcgroup/oxdna-viewer#62]
I observe a problem with the master branch in that there's simply no configuration displayed at all. What I do is I open 'index.html' as file in my browser (Firefox and Chrome).

The last working commit is
```
commit 530fa4f43b3fcee01d01b1999fbbb6735ac88a79
Merge: f403119 c99742b
Author: ErikPoppleton <rkpoppleton@gmail.com>
Date:   Thu Jun 17 14:57:40 2021 -0700

    Merge branch 'master' of https://github.com/sulcgroup/oxdna-viewer
```
Anything later shows the above mentioned problem. 

I attach a configuration and topology file, which should allow you to check this. Many thanks.
[files.zip](https://github.com/sulcgroup/oxdna-viewer/files/7236039/files.zip)

**Comment by m-matthies** [comment]
Hi Oliver, we no longer support the feature where you just can open the index.html. 
Most of our new features require a webserver for the page to work. 
If you want to run it locally just use any development server like:
`python -m http.server 8000` (command needs to be run in the oxdna-viewer directory. )
The page will be available @ localhost:8000
Alternatively you can try out our standalone executable version:
https://github.com/sulcgroup/oxdna-viewer/releases/tag/v1.0.1

**Comment by ohenrich** [comment]
Hi Michael, Thanks a lot -- I wasn't aware of this change. There's unfortunately no executable for Mac (I think Petr said he can't compile for one). Let me know if I can help here, but I would need some instructions ...
Regarding running locally: Is this information also somewhere in the documentation? It's because I would like to point people towards something.

**Comment by m-matthies** [comment]
Thanks for pointing it out, I've updated the corresponding section. 
https://github.com/sulcgroup/oxdna-viewer/blob/master/README.md#updates-and-writing-your-own-extensions-or-running-oxview-locally
On the electron build for mac. Doing the `npm install` (from the previous step) should download all the necessary  libraries to compile a mac executable on an mac machine. It should be as easy as running `npm run make` in the oxView folder.
This would generate an `out` folder which should contain the executable.

**Comment by m-matthies** [comment]
If this works we would be very happy to add it to the list of provided executables.
