### ISSUE TITLE
PDB biological assembly support

### ISSUE THREAD

**Issue by DurhamSmith** [sulcgroup/oxdna-viewer#63]
Is there any way when importing a PBD file, of say a virus, to have it create the full biological assembly (https://pdb101.rcsb.org/learn/guide-to-understanding-pdb-data/biological-assemblies) not just display the minimal unit cell?

**Comment by Jonahowns** [comment]
Hello,
Currently our PDB importer only loads what is provided in the pdb file. So a file containing only the minimal unit cell will only load the minimal unit cell. To load a complete biological assembly, you need to have a pdb containing coordinates of all unit cells in the assembly. These files are usually readily available from the RCSB by navigating to the entry, clicking the "Download Files" to open the dropdown menu and selecting biological assembly. After downloading and extracting the file you should have a pdb file of the biological assembly that you can drag and drop onto oxView to open. 

As an example you can try out this entry: https://www.rcsb.org/structure/1AL0 

Let me know if you have any questions or need further assistance!

**Comment by DurhamSmith** [comment]
Thanks @Jonahowns!
