### ISSUE TITLE
Feature request: UI shortcut for toggleBaseColors(), also option to change base colors from default grey

### ISSUE THREAD

**Issue by dhollis6** [sulcgroup/oxdna-viewer#85]
When I'm creating images I often find myself going into the scene api files to change assignment of toggleBaseColors() to a different color, then calling this function in the api. Would be nice to have a button for this in the Colors section of the View tab. (As far as I know the Edit Color Palette option only affects backbone colors...)

edit: terminology

**Comment by m-matthies** [comment]
If you have a visual style you usually adhere to, i would suggest to have a style.js
script file doing smth along the lines of:
```js 
// define new colors for the nucleotides.
nucleosideColors = [new THREE.Color(0x5E005E),new THREE.Color(0x5E005E),new THREE.Color(0x5E005E),new THREE.Color(0x5E005E),];
// needs to be toggled twice to switch between Grey and Color
api.toggleBaseColors();api.toggleBaseColors();
```
which you drag drop on the scene, instead of setting things in the UI
