### ISSUE TITLE
Feature request: NickOrientation handles 1 or 2 nucleotides

### ISSUE THREAD

**Issue by dhollis6** [sulcgroup/oxdna-viewer#86]
I'm doing a lot of analyses which involve the poloidal angle of single nucleotides... it would help to modify NickOrientation so that if only one nucleotide is selected, and you call api.observable.NickOrientation(Array.from(selectedBases)) it will draw a vector extending from the center of the helix through the backbone of that nucleotide.

In this case it should be renamed, since it wouldn't only work for nicks but also for individual nucleotides. Took me only 30 seconds to change this in observable_api.js, just not sure which branch to push to or how that all works... figured I would post here instead :)

**Comment by m-matthies** [comment]
Hi, I updated the code.
the new observable is called MeanOrientation
here's an example:

```js
let s = edit.createStrand("NNNNNNNNNNNNNNNNNNNNN",true);
 
let ori =  new api.observable.MeanOrientation(s.slice(2,4));
render = api.observable.wrap(render, () => {ori.update()});
render();
```

also for future tunings like this i would probably keep this to scripts,
as  you can now drag/drop a script file onto view.

I removed the old NickOrientation completely.
