### ISSUE TITLE
Just a quick fix for the overlays scales?

### ISSUE THREAD

**Issue by simonecodispoti** [sulcgroup/oxdna-viewer#88]
I wrongly posted this issue on the 'oxdna' repo:

[https://github.com/lorenzo-rovigatti/oxDNA/issues/38#issue-1384996358](https://github.com/lorenzo-rovigatti/oxDNA/issues/38#issue-1384996358)

Thanks for considering it,
Simone

**Comment by ErikPoppleton** [comment]
Hi Simone,

Do you have examples of overlay files that do and don't work?  Is it consistent?

**Comment by simonecodispoti** [comment]
Hi! Yes, I'll post here an example of working and non working files with pictures. It is pretty consistent with different `json` files and I think It's correlated to how much the scale of the observable is stretched: look at _Backbone_exluded_volume_ VS _Total_ and at the corresponding `json` files:

BACKBONE

{
"Back-ex-vol [pN nm]" : [0.0025826550185651703, 0.0071415157896611734, 0.0076746184434620035, 0.007349976376043002, 0.007084260294139301, 0.0045242023837593, 0.004423686091928223, 0.004542558524185224, 0.006059274405341501, 0.006618878158688003, 0.0039153139700135, 0.004006814942753002, 0.005092012392132368, 0.005856319447178668, 0.006336110560414299, 0.0056661499136463, 0.004709967837466799, 0.004284255402578499, 0.0037046744131443007, 0.0038616162867495005, 0.0053156674144656, 0.00553185134627179, 0.00615587484008799, 0.005916763196984999, 0.0068375516971887025, 0.007226535991150941, 0.0045908715993642464, 0.0019551012180636074]
}

<img width="857" alt="Schermata 2022-09-30 alle 15 13 49" src="https://user-images.githubusercontent.com/62181811/193277880-4e59ffb2-fc83-4b0d-b31d-678566f90691.png">

TOTAL

{
"Total [pN nm]" : [-42.7297636491767, -74.65331870033846, -66.54574933345542, -74.05847384402865, -78.07624073971738, -78.80869278900413, -74.54886117847886, -71.17315624532495, -69.17505913611262, -66.39547993075972, -73.96236888394621, -73.89692213946728, -71.31639288307352, -70.21659741149334, -71.34643450393797, -71.3790229707479, -75.89126561366662, -82.04725875811944, -72.2159482070154, -68.24635292401233, -77.31961103640107, -80.54587925047645, -64.68528304085376, -60.25092333341516, -68.84346158628416, -77.58043006536838, -86.43778618115053, -46.375482811669514]
}

<img width="1025" alt="Schermata 2022-09-30 alle 15 18 01" src="https://user-images.githubusercontent.com/62181811/193278347-61240450-e918-4a08-9ee2-0cac2b38a163.png">

**Comment by ErikPoppleton** [comment]
Hi Simone, you're correct that it has to do with the numbers in the file.  Right now, the colorbar is set to use two decimals, which is 0.00 for all of the values in your not-working example.  If I set it to 3, it works, but becomes very ugly.  I will investigate if I can maybe change it to use scientific notation, but failing at that I will at least add a helpful warning message about values being too close together.

![image](https://user-images.githubusercontent.com/36451772/193332412-e5a3fa85-44e0-49b1-b58b-b9209fa64403.png)

**Comment by ErikPoppleton** [comment]
The colorbar will now display values with spacing less than 0.09 in scientific notation.
